# Generated by Django 5.0.3 on 2024-03-15 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='password',
        ),
        migrations.AddField(
            model_name='school',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
