# Generated by Django 5.0.3 on 2024-04-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_announcement_assignment_assignmentsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grade',
            field=models.CharField(choices=[('1', 'First Grade'), ('2', 'Second Grade'), ('3', 'Third Grade'), ('4', 'Fourth Grade'), ('5', 'Fifth Grade'), ('6', 'Sixth Grade'), ('7', 'Seventh Grade'), ('8', 'Eighth Grade')], max_length=2, null=True),
        ),
    ]
