# Generated by Django 5.0.3 on 2024-04-24 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_assignment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.school'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_grade', to='school.teacher'),
        ),
    ]
