# Generated by Django 5.0.3 on 2024-08-10 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_channel_users_alter_channel_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='channel',
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_grade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_teacher', to='school.grade'),
        ),
    ]
