# Generated by Django 5.0.3 on 2024-08-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_remove_teacher_grade_remove_user_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='teacher',
        ),
    ]
