# Generated by Django 5.0.3 on 2024-08-10 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_remove_grade_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='assigned_grade',
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_grade', to='school.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='grade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_teacher', to='school.grade'),
        ),
    ]
