# Generated by Django 5.0.3 on 2024-08-15 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_remove_teacher_assigned_grade_grade_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='creator',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='created_channels', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
