# Generated by Django 5.0.3 on 2024-09-21 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_remove_event_related_entities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, default='2024-04-27'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedules',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='schedules/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
