# Generated by Django 5.0.3 on 2024-09-25 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_alter_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='school.school'),
        ),
    ]
