# Generated by Django 5.0.3 on 2024-09-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_announcement_teacher_alter_announcement_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
