# Generated by Django 5.0.3 on 2024-09-27 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_delete_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.grade'),
        ),
    ]
