# Generated by Django 5.0.3 on 2024-10-04 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_alter_assignment_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
